// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp7IL_3mKezygtJ7XIgPQKOQc68-YWG6U',
    appId: '1:957105516993:web:632a6f4993407bc12e7f40',
    messagingSenderId: '957105516993',
    projectId: 'step-stalk',
    authDomain: 'step-stalk.firebaseapp.com',
    storageBucket: 'step-stalk.firebasestorage.app',
    measurementId: 'G-JWSY0SEWQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1wReEW9dArkptc2RAZqpAAlTGpkUaC40',
    appId: '1:957105516993:android:2d9dc767a29ee3712e7f40',
    messagingSenderId: '957105516993',
    projectId: 'step-stalk',
    storageBucket: 'step-stalk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCwI9OSbYjHxfAAOocySsjjfXavn2H3c8',
    appId: '1:957105516993:ios:125accaca25d8d6f2e7f40',
    messagingSenderId: '957105516993',
    projectId: 'step-stalk',
    storageBucket: 'step-stalk.firebasestorage.app',
    iosBundleId: 'com.example.stepstalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCwI9OSbYjHxfAAOocySsjjfXavn2H3c8',
    appId: '1:957105516993:ios:125accaca25d8d6f2e7f40',
    messagingSenderId: '957105516993',
    projectId: 'step-stalk',
    storageBucket: 'step-stalk.firebasestorage.app',
    iosBundleId: 'com.example.stepstalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp7IL_3mKezygtJ7XIgPQKOQc68-YWG6U',
    appId: '1:957105516993:web:9949c2081672b5842e7f40',
    messagingSenderId: '957105516993',
    projectId: 'step-stalk',
    authDomain: 'step-stalk.firebaseapp.com',
    storageBucket: 'step-stalk.firebasestorage.app',
    measurementId: 'G-B5DVK67TDZ',
  );

}